from __future__ import annotations

from decimal import Decimal

MONEY_PRECISION = Decimal("0.01")
PROBABILITY_PRECISION = Decimal("0.000001")
THE_ODDS_API_DEFAULT_MARKETS = "h2h"
ARBITRAGE_DETECTION_MARKETS = ("h2h",)
SCAN_PRIORITY_LOW = "LOW"
SCAN_PRIORITY_NORMAL = "NORMAL"
SCAN_PRIORITY_HIGH = "HIGH"
SCAN_PRIORITY_URGENT = "URGENT"
SCAN_PRIORITY_LEVELS = (
    SCAN_PRIORITY_LOW,
    SCAN_PRIORITY_NORMAL,
    SCAN_PRIORITY_HIGH,
    SCAN_PRIORITY_URGENT,
)
MARKET_QUALITY_VERIFIED = "VERIFIED"
MARKET_QUALITY_RISKY = "RISKY"
MARKET_QUALITY_STALE = "STALE"
MARKET_QUALITY_REJECTED = "REJECTED"
MARKET_QUALITY_STATUSES = (
    MARKET_QUALITY_VERIFIED,
    MARKET_QUALITY_RISKY,
    MARKET_QUALITY_STALE,
    MARKET_QUALITY_REJECTED,
)
EXECUTION_STATUS_PLANNED = "PLANNED"
EXECUTION_STATUS_ACTIONED = "ACTIONED"
EXECUTION_STATUS_PARTIALLY_ACTIONED = "PARTIALLY_ACTIONED"
EXECUTION_STATUS_ODDS_CHANGED = "ODDS_CHANGED"
EXECUTION_STATUS_SKIPPED = "SKIPPED"
EXECUTION_STATUS_SETTLED = "SETTLED"
EXECUTION_STATUSES = (
    EXECUTION_STATUS_PLANNED,
    EXECUTION_STATUS_ACTIONED,
    EXECUTION_STATUS_PARTIALLY_ACTIONED,
    EXECUTION_STATUS_ODDS_CHANGED,
    EXECUTION_STATUS_SKIPPED,
    EXECUTION_STATUS_SETTLED,
)
EXECUTION_LEG_STATUS_PLANNED = "PLANNED"
EXECUTION_LEG_STATUS_PLACED = "PLACED"
EXECUTION_LEG_STATUS_SKIPPED = "SKIPPED"
EXECUTION_LEG_STATUS_ODDS_CHANGED = "ODDS_CHANGED"
EXECUTION_LEG_STATUSES = (
    EXECUTION_LEG_STATUS_PLANNED,
    EXECUTION_LEG_STATUS_PLACED,
    EXECUTION_LEG_STATUS_SKIPPED,
    EXECUTION_LEG_STATUS_ODDS_CHANGED,
)

SUPPORTED_OPPORTUNITY_ACTION_TYPES = {
    "VIEWED",
    "ACTIONED",
    "SKIPPED",
    "EXPIRED",
    "ODDS_CHANGED",
    "BET_REJECTED",
    "WON",
    "LOST",
}
