from __future__ import annotations

from decimal import Decimal

MONEY_PRECISION = Decimal("0.01")
PROBABILITY_PRECISION = Decimal("0.000001")
THE_ODDS_API_DEFAULT_MARKETS = "h2h"
SCAN_PRIORITY_LOW = "LOW"
SCAN_PRIORITY_NORMAL = "NORMAL"
SCAN_PRIORITY_HIGH = "HIGH"
SCAN_PRIORITY_URGENT = "URGENT"
SCAN_PRIORITY_LEVELS = (
    SCAN_PRIORITY_LOW,
    SCAN_PRIORITY_NORMAL,
    SCAN_PRIORITY_HIGH,
    SCAN_PRIORITY_URGENT,
)

SUPPORTED_OPPORTUNITY_ACTION_TYPES = {
    "VIEWED",
    "ACTIONED",
    "SKIPPED",
    "EXPIRED",
    "ODDS_CHANGED",
    "BET_REJECTED",
    "WON",
    "LOST",
}
